from __future__ import annotations

from textwrap import dedent

from cardiomas.schemas.config import RuntimeConfig
from cardiomas.schemas.tools import ToolSpec


def build_generated_tool_package(
    tool_name: str,
    payload: dict,
    config: RuntimeConfig,
    last_error: str = "",
) -> tuple[ToolSpec, str, str]:
    if tool_name == "read_dataset_file":
        return _build_file_reader_tool(last_error)
    if tool_name == "dataset_statistics":
        return _build_dataset_statistics_tool(last_error)
    raise ValueError(f"Unsupported generated tool: {tool_name}")


def _build_file_reader_tool(last_error: str) -> tuple[ToolSpec, str, str]:
    spec = ToolSpec(
        name="read_dataset_file",
        description="Generated dataset file reader that reuses repository format readers and safe local previews.",
        category="autonomy",
        generated=True,
    )
    readme = dedent(
        f"""\
        # Generated File Reader

        This tool was generated by CardioMAS autonomy to inspect local dataset files safely.
        Last observed error during generation cycle: {last_error or "(none)"}.
        """
    )
    code = dedent(
        """\
        from __future__ import annotations

        import json
        from pathlib import Path

        from cardiomas.mappers.format_readers.csv_reader import read_csv
        from cardiomas.mappers.format_readers.edf_reader import read_edf_directory
        from cardiomas.mappers.format_readers.hdf5_reader import read_hdf5, read_hdf5_directory
        from cardiomas.mappers.format_readers.numpy_reader import read_numpy_directory
        from cardiomas.mappers.format_readers.wfdb_reader import read_wfdb_directory


        def run(payload: dict) -> dict:
            dataset_path = Path(str(payload.get("dataset_path", ""))).expanduser()
            target_path = Path(str(payload.get("target_path", ""))).expanduser() if payload.get("target_path") else Path()
            preview_lines = int(payload.get("max_preview_lines", 40))

            selected = _resolve_target(dataset_path, target_path)
            if selected is None:
                return {"ok": False, "summary": "", "error": "No readable file or dataset target could be resolved."}

            result = _inspect_target(selected, dataset_path, preview_lines)
            if not result.get("ok", False):
                return result

            content = result["data"].get("preview_text") or json.dumps(result["data"], indent=2, default=str)
            evidence = [
                {
                    "chunk_id": f"generated-file-reader:{selected}",
                    "source_id": "autonomy",
                    "source_label": "generated-file-reader",
                    "source_type": "generated_tool",
                    "title": selected.name,
                    "content": content[:4000],
                    "uri": str(selected),
                    "metadata": {"chunk_label": selected.name, "path": str(selected)},
                    "score": 1.0,
                }
            ]
            result["evidence"] = evidence
            return result


        def _resolve_target(dataset_path: Path, target_path: Path) -> Path | None:
            if target_path and target_path.exists():
                return target_path
            if dataset_path and dataset_path.exists():
                if dataset_path.is_file():
                    return dataset_path
                preferred_suffixes = [".csv", ".tsv", ".hea", ".h5", ".hdf5", ".npy", ".npz", ".edf", ".txt", ".md", ".json", ".html"]
                files = sorted(path for path in dataset_path.rglob("*") if path.is_file())
                for suffix in preferred_suffixes:
                    for path in files:
                        if path.suffix.lower() == suffix:
                            return path
                return files[0] if files else dataset_path
            return None


        def _inspect_target(path: Path, dataset_root: Path, preview_lines: int) -> dict:
            suffix = path.suffix.lower()
            if path.is_dir():
                if list(path.rglob("*.hea")):
                    data = read_wfdb_directory(str(path))
                    return _result(path, "wfdb_directory", data)
                if list(path.rglob("*.edf")):
                    data = read_edf_directory(str(path))
                    return _result(path, "edf_directory", data)
                if list(path.rglob("*.h5")) or list(path.rglob("*.hdf5")):
                    data = read_hdf5_directory(str(path))
                    return _result(path, "hdf5_directory", data)
                if list(path.rglob("*.npy")) or list(path.rglob("*.npz")):
                    data = read_numpy_directory(str(path))
                    return _result(path, "numpy_directory", data)
                return {"ok": False, "summary": "", "error": f"Directory {path} does not match a supported generated reader type."}

            if suffix in {".csv", ".tsv"}:
                data = read_csv(str(path))
                return _result(path, "csv_reader", data)
            if suffix == ".hea":
                data = read_wfdb_directory(str(path.parent))
                data["selected_record"] = path.stem
                return _result(path, "wfdb_reader", data)
            if suffix in {".h5", ".hdf5"}:
                data = read_hdf5(str(path))
                return _result(path, "hdf5_reader", data)
            if suffix in {".npy", ".npz"}:
                data = read_numpy_directory(str(path.parent))
                data["selected_file"] = path.name
                return _result(path, "numpy_reader", data)
            if suffix == ".edf":
                data = read_edf_directory(str(path.parent))
                data["selected_file"] = path.name
                return _result(path, "edf_reader", data)
            if suffix in {".txt", ".md", ".json", ".html", ".yml", ".yaml"}:
                text = path.read_text(encoding="utf-8", errors="ignore")
                preview = "\\n".join(text.splitlines()[:preview_lines])
                data = {
                    "selected_path": str(path),
                    "reader": "text_preview",
                    "preview_text": preview,
                    "size_bytes": path.stat().st_size,
                }
                return {
                    "ok": True,
                    "summary": f"Read text preview from {path.name}",
                    "data": data,
                }

            data = {
                "selected_path": str(path),
                "reader": "binary_metadata",
                "size_bytes": path.stat().st_size,
                "suffix": suffix or "<no_extension>",
            }
            return {"ok": True, "summary": f"Captured binary metadata for {path.name}", "data": data}


        def _result(path: Path, reader: str, data: dict) -> dict:
            output = dict(data)
            output["selected_path"] = str(path)
            output["reader"] = reader
            if "preview_text" not in output:
                output["preview_text"] = json.dumps(output, indent=2, default=str)[:4000]
            return {
                "ok": "error" not in output,
                "summary": f"Generated reader {reader} inspected {path.name}",
                "data": output,
                "error": str(output.get("error", "")),
            }
        """
    )
    return spec, code, readme


def _build_dataset_statistics_tool(last_error: str) -> tuple[ToolSpec, str, str]:
    spec = ToolSpec(
        name="dataset_statistics",
        description="Generated dataset statistics tool for local directories and CSV-like metadata files.",
        category="autonomy",
        generated=True,
    )
    readme = dedent(
        f"""\
        # Generated Dataset Statistics Tool

        This tool was generated by CardioMAS autonomy to compute summary statistics.
        Last observed error during generation cycle: {last_error or "(none)"}.
        """
    )
    code = dedent(
        """\
        from __future__ import annotations

        import csv
        from pathlib import Path


        def run(payload: dict) -> dict:
            dataset_path = Path(str(payload.get("dataset_path", ""))).expanduser()
            target_file_value = str(payload.get("target_file", "")).strip()
            target_file = Path(target_file_value).expanduser() if target_file_value else None

            if target_file is not None and target_file.exists():
                target = target_file
            else:
                target = _choose_target_file(dataset_path)

            dataset_summary = _dataset_file_summary(dataset_path) if dataset_path and dataset_path.exists() else {}

            if target is None:
                return {
                    "ok": True,
                    "summary": "Computed dataset-level file statistics without a tabular target file.",
                    "data": {"dataset_summary": dataset_summary, "analyzed_file": ""},
                    "evidence": [_dataset_evidence(dataset_path, dataset_summary)],
                }

            if target.suffix.lower() not in {".csv", ".tsv"}:
                return {
                    "ok": True,
                    "summary": f"Computed file-level metadata for non-tabular target {target.name}.",
                    "data": {
                        "dataset_summary": dataset_summary,
                        "analyzed_file": str(target),
                        "columns": [],
                        "total_rows": 0,
                        "numeric_summary": {},
                        "class_counts": {},
                    },
                    "evidence": [_file_evidence(target, f"Non-tabular target selected: {target.name}")],
                }

            rows = _read_rows(target)
            if not rows:
                return {"ok": False, "summary": "", "error": f"No rows could be read from {target}"}

            headers = rows[0]
            data_rows = rows[1:]
            numeric_summary = _numeric_summary(headers, data_rows)
            class_counts = _class_counts(headers, data_rows)
            missing_fraction = _missing_fraction(data_rows)
            summary = f"Generated stats over {len(data_rows)} row(s) and {len(headers)} column(s) from {target.name}."
            data = {
                "dataset_summary": dataset_summary,
                "analyzed_file": str(target),
                "columns": headers,
                "total_rows": len(data_rows),
                "numeric_summary": numeric_summary,
                "class_counts": class_counts,
                "missing_fraction": missing_fraction,
            }
            evidence_text = _format_stats_text(target, data)
            return {
                "ok": True,
                "summary": summary,
                "data": data,
                "evidence": [_file_evidence(target, evidence_text)],
            }


        def _choose_target_file(dataset_path: Path) -> Path | None:
            if not dataset_path or not dataset_path.exists():
                return None
            if dataset_path.is_file():
                return dataset_path
            csv_files = sorted([path for path in dataset_path.rglob("*") if path.is_file() and path.suffix.lower() in {".csv", ".tsv"}], key=lambda item: item.stat().st_size, reverse=True)
            return csv_files[0] if csv_files else None


        def _dataset_file_summary(dataset_path: Path) -> dict:
            if not dataset_path or not dataset_path.exists():
                return {}
            root = dataset_path if dataset_path.is_dir() else dataset_path.parent
            files = sorted(path for path in root.rglob("*") if path.is_file())
            extension_counts = {}
            for path in files:
                suffix = path.suffix.lower() or "<no_extension>"
                extension_counts[suffix] = extension_counts.get(suffix, 0) + 1
            return {
                "dataset_path": str(root),
                "total_files": len(files),
                "extension_counts": extension_counts,
            }


        def _read_rows(path: Path) -> list[list[str]]:
            sep = "\\t" if path.suffix.lower() == ".tsv" else ","
            with path.open("r", encoding="utf-8", newline="") as handle:
                reader = csv.reader(handle, delimiter=sep)
                rows = []
                for index, row in enumerate(reader):
                    rows.append(row)
                    if index >= 5000:
                        break
            return rows


        def _numeric_summary(headers: list[str], rows: list[list[str]]) -> dict:
            result = {}
            for column_index, name in enumerate(headers[:20]):
                values = []
                for row in rows:
                    if column_index >= len(row):
                        continue
                    value = row[column_index].strip()
                    if not value:
                        continue
                    try:
                        values.append(float(value))
                    except ValueError:
                        continue
                if values:
                    result[name] = {
                        "count": len(values),
                        "mean": round(sum(values) / len(values), 4),
                        "min": min(values),
                        "max": max(values),
                    }
                if len(result) >= 8:
                    break
            return result


        def _class_counts(headers: list[str], rows: list[list[str]]) -> dict:
            label_candidates = {"label", "labels", "rhythm", "diagnosis", "diagnoses", "scp_codes", "class", "target"}
            selected_index = None
            selected_name = ""
            for index, name in enumerate(headers):
                if name.strip().lower() in label_candidates:
                    selected_index = index
                    selected_name = name
                    break
            if selected_index is None:
                return {}

            counts = {}
            for row in rows:
                if selected_index >= len(row):
                    continue
                value = row[selected_index].strip()
                if not value:
                    continue
                counts[value] = counts.get(value, 0) + 1
            limited = dict(sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:20])
            return {"column": selected_name, "counts": limited}


        def _missing_fraction(rows: list[list[str]]) -> float:
            if not rows:
                return 0.0
            missing_cells = 0
            total_cells = 0
            for row in rows:
                total_cells += len(row)
                missing_cells += sum(1 for value in row if not value.strip())
            return round(missing_cells / total_cells, 6) if total_cells else 0.0


        def _format_stats_text(target: Path, data: dict) -> str:
            return (
                f"Statistics for {target.name}\\n"
                f"Rows: {data['total_rows']}\\n"
                f"Columns: {', '.join(data['columns'][:20])}\\n"
                f"Missing fraction: {data['missing_fraction']}\\n"
                f"Numeric summary: {data['numeric_summary']}\\n"
                f"Class counts: {data['class_counts']}"
            )


        def _dataset_evidence(dataset_path: Path, dataset_summary: dict) -> dict:
            return {
                "chunk_id": f"generated-dataset-summary:{dataset_path}",
                "source_id": "autonomy",
                "source_label": "generated-dataset-statistics",
                "source_type": "generated_tool",
                "title": dataset_path.name or "dataset",
                "content": str(dataset_summary),
                "uri": str(dataset_path),
                "metadata": {"chunk_label": dataset_path.name or "dataset"},
                "score": 1.0,
            }


        def _file_evidence(target: Path, content: str) -> dict:
            return {
                "chunk_id": f"generated-dataset-statistics:{target}",
                "source_id": "autonomy",
                "source_label": "generated-dataset-statistics",
                "source_type": "generated_tool",
                "title": target.name,
                "content": content[:4000],
                "uri": str(target),
                "metadata": {"chunk_label": target.name, "path": str(target)},
                "score": 1.0,
            }
        """
    )
    return spec, code, readme
