from __future__ import annotations

import json
import logging

from cardiomas.schemas.state import GraphState, LogEntry
from cardiomas.security.audit import run_security_audit
from cardiomas.verbose import vprint

logger = logging.getLogger(__name__)


def security_agent(state: GraphState) -> GraphState:
    """Run security and data-leak audit on proposed splits."""
    state.execution_log.append(LogEntry(agent="security", action="start"))
    vprint("security", "running PII, raw-data, and leakage audit…")

    if state.proposed_splits is None:
        state.errors.append("security_agent: no proposed_splits to audit")
        return state

    splits = state.proposed_splits.splits
    total_ids = sum(len(v) for v in splits.values())
    vprint("security", f"auditing {total_ids} record IDs across {list(splits.keys())}")

    # ── Phase 2: use real patient_record_map from DatasetMap ──────────────
    patient_mapping = _get_patient_mapping(state)
    if patient_mapping:
        vprint("security", f"using real patient mapping ({len(patient_mapping)} patients)")
    else:
        vprint("security", "no patient mapping available — leakage check limited to record IDs")

    audit = run_security_audit(splits, patient_mapping=patient_mapping)
    state.security_audit = audit

    if not audit.passed:
        for issue in audit.blocking_issues:
            state.errors.append(f"Security: {issue}")
            vprint("security", f"[red]BLOCKED: {issue}[/red]")
        state.execution_log.append(
            LogEntry(agent="security", action="FAILED", detail=str(audit.blocking_issues))
        )
    else:
        vprint("security", "audit PASSED — no PII, no raw data, no leakage")
        state.execution_log.append(LogEntry(agent="security", action="PASSED"))

    return state


def _get_patient_mapping(state: GraphState) -> dict[str, list[str]] | None:
    """Extract patient_record_map — V4 executor output > V3 DatasetMap."""
    # V4: check patient_map.json generated by 01_extract_metadata.py
    v4_mapping = _get_patient_mapping_v4(state)
    if v4_mapping:
        return v4_mapping

    # V3 fallback: DatasetMap
    return _get_patient_mapping_v3(state)


def _get_patient_mapping_v4(state: GraphState) -> dict[str, list[str]] | None:
    """Read patient_record_map from V4 executor-generated patient_map.json."""
    patient_map_json = state.v4_generated_files.get("patient_map.json", "")
    if not patient_map_json:
        return None
    try:
        mapping = json.loads(patient_map_json)
        if isinstance(mapping, dict) and mapping:
            return mapping
    except Exception as e:
        logger.debug(f"security: could not parse patient_map.json: {e}")
    return None


def _get_patient_mapping_v3(state: GraphState) -> dict[str, list[str]] | None:
    """Extract patient_record_map from V3 DatasetMap if available."""
    dataset_map = getattr(state, "dataset_map", None)
    if dataset_map is None:
        analysis = state.analysis_report or {}
        dataset_map = analysis.get("dataset_map")

    if dataset_map is None:
        return None

    mapping = None
    if hasattr(dataset_map, "patient_record_map"):
        mapping = dataset_map.patient_record_map
    elif isinstance(dataset_map, dict):
        mapping = dataset_map.get("patient_record_map")

    return mapping if mapping else None
